.TH "irc_ctx_t" 3 "12 Jun 2012" "Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc_ctx_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <irc.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBchannel\fP"
.br
.ti -1c
.RI "char * \fBnick\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char* \fBirc_ctx_t::channel\fP"
.PP
.SS "char* \fBirc_ctx_t::nick\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bot from the source code.
