.TH "src/main.cpp" 3 "12 Jun 2012" "Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include '../include/sqlite3.h'\fP
.br
\fC#include '../include/libircclient.h'\fP
.br
\fC#include '../include/irc.h'\fP
.br
\fC#include '../include/log.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Main application. Use config file if shell is not used. Creates irc connection. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Bot from the source code.
