.TH "sqlite3_file" 3 "12 Jun 2012" "Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_file \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBsqlite3_io_methods\fP * \fBpMethods\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBsqlite3_io_methods\fP* \fBsqlite3_file::pMethods\fP\fC [read]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bot from the source code.
