.TH "sqlite3_index_info::sqlite3_index_constraint" 3 "12 Jun 2012" "Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_index_info::sqlite3_index_constraint \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiColumn\fP"
.br
.ti -1c
.RI "unsigned char \fBop\fP"
.br
.ti -1c
.RI "unsigned char \fBusable\fP"
.br
.ti -1c
.RI "int \fBiTermOffset\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fBsqlite3_index_info::sqlite3_index_constraint::iColumn\fP"
.PP
.SS "unsigned char \fBsqlite3_index_info::sqlite3_index_constraint::op\fP"
.PP
.SS "unsigned char \fBsqlite3_index_info::sqlite3_index_constraint::usable\fP"
.PP
.SS "int \fBsqlite3_index_info::sqlite3_index_constraint::iTermOffset\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bot from the source code.
