.TH "sqlite3_pcache_page" 3 "12 Jun 2012" "Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sqlite3_pcache_page \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBpBuf\fP"
.br
.ti -1c
.RI "void * \fBpExtra\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "void* \fBsqlite3_pcache_page::pBuf\fP"
.PP
.SS "void* \fBsqlite3_pcache_page::pExtra\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Bot from the source code.
